export const browseTypes = {
  UPDATE_BROWSE_SEARCH_CRITERIA: 'UPDATE_BROWSE_CRITERIA', 
   UPDATE_BROWSE_SEARCH_TERM: 'UPDATE_BROWSE_SEARCH_TERM',   
   UPDATE_BROwSE_SEARCH_RESULTS: 'UPDATE_BROWSE_SEARCH_RESULTS',  
}
