export const buyerTypes = {
  ADD_TO_BIDS: "ADD_TO_BIDS",
  ADD_TO_BOUGHT: "ADD_TO_BOUGHT",
  GET_BUYER: "GET_BUYER",
  POST_NEW_BUYER: "POST_NEW_BUYER",
  PUT_NEW_BID: "PUT_NEW_BID",
  REINITIALIZE_BUYER: "REINITIALIZE_BUYER",
  UPDATE_BID_PRICE: "UPDATE_BID_PRICE",
  UPDATE_BID_SELLER: "UPDATE_BID_SELLER",
  UPDATE_BOUGHT_PRICE: "UPDATE_BOUGHT_PRICE",
  UPDATE_BOUGHT_SELLER: "UPDATE_BOUGHT_SELLER",
  UPDATE_BOUGHT_TIME: "UPDATE_BOUGHT_TIME",
  UPDATE_ITEM_NAME_BOUGHT: "UPDATE_ITEM_NAME_BOUGHT",
  UPDATE_POST_TIME_BID: "UPDATE_POST_TIME_BID",
  UPDATE_POST_TIME_BOUGHT: "UPDATE_POST_TIME_BOUGHT"
};
