export const userTypes = {
  REINITIALIZE_USER: 'REINITIALIZE_USER',
  UPDATE_AUTH_TOKEN: 'UPDATE_AUTH_TOKEN', 
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_ERROR: 'UPDATE_ERROR',
  UPDATE_FAMILY_NAME: 'UPDATE_FAMILY_NAME',
  UPDATE_GIVEN_NAME: 'UPDATE_GIVEN_NAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
}